print("Hallo, ik ga je enkele vragen stellen. Deze vragen gebruik ik om een verhaal te genereren.")
print()
zus = input("Wat is de naam van jouw zus? ")
leuk = input("Wat vind je leuk om te doen? ")
haat = input("Wat haat je om te doen? ")
print()
print("Jouw gegenereerde verhaal:")
print("__________________________")
print("Jouw zus heet", "\033[31m", zus, "\033[0m", "en je vindt het leuk om te", leuk, "en je haat het om te", haat)
print()
print("Dank voor je aandacht.")